name: Run Pylint On Project
on:
  push:
    branches:
      - "main"
jobs:
  Run-Linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: sunnysid3up/python-linter@master
